### ISSUE TITLE
Feature Request: border setting for each column

### ISSUE THREAD

**Issue by bucketpress** [kadencethemes/kadence-blocks#10]
Hi, allowing users to set up borders like how currently we are able to set up padding and margins for each column will be very useful. This will help users create card-like layouts and design. Users can set up borders by specifying thickness of top, right, bottom and left borders. To not over-complicate usability, a single selection of border color will be applied to all 4 sides, I'm thinking that the css should be applied to the .kt-inside-inner-col element, similar to padding and margins.

**Comment by kadencethemes** [comment]
Good suggestion, I'll add it to my todo list.

Ben

**Comment by kadencethemes** [comment]
Closing this was added.
