### ISSUE TITLE
Error: kt_blocks_default_size is not defined

### ISSUE THREAD

**Issue by bucketpress** [kadencethemes/kadence-blocks#11]
Browser dev console returns this error when running.

**Comment by kadencethemes** [comment]
interesting, in your settings > kadence blocks do you have widths defined for the editor.

Ben

**Comment by bucketpress** [comment]
In the settings I had set Enable Editor Width to False previously. I have reset it to True, and then set it as False again and the error is gone. Seems like an initialization issue?

**Comment by kadencethemes** [comment]
I think I have this resolved.
