### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by milind1983** [kadencethemes/kadence-blocks#12]
Hello,

I am referring your code and found this code in blocks files. Can you please let us know why this code is needed? Is this useful for translating java script strings to .PO files? Why we use `setLocaleData` as we dont find it is useful anywhere in your plugins files?

`wp.i18n.setLocaleData( { '': {} }, 'ultimate-addons-for-gutenberg' );`

Any help will be really appreciable.

Regards,
Milind.

**Comment by kadencethemes** [comment]
Hey, 

Looks like you are posting code from 'ultimate-addons-for-gutenberg'
Using setLocaleData is very important for translating javascript strings through a po file. And the code you posted it normal and we have similar. 

https://github.com/kadencethemes/kadence-blocks/blob/51485edb8928810e877d968cfb806d0f15bff0fc/src/blocks.js#L5

Does that help?
