### ISSUE TITLE
Parent-dependent child blocks should be hidden from the inserter

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#15]
Blocks such as "Column" and "Tab" must be located within their respective parent blocks in order to function properly.

These blocks should be hidden from the block inserter by using the proper configuration in the ["supports" array](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#supports-optional) during block registration.

They should probably also use the ["parent" array](https://wordpress.org/gutenberg/handbook/designers-developers/developers/block-api/block-registration/#parent-optional) to restrict which parents they can be inserted into.

**Comment by kadencethemes** [comment]
Hey, Both column and tab should already be hidden. How do you create a way to insert them currently?

https://github.com/kadencethemes/kadence-blocks/blob/master/src/blocks/column/block.js#L38

**Comment by rchipka** [comment]
```js
supports: {
  inserter: false,
},
```

**Comment by kadencethemes** [comment]
What version of Gutenberg are you using?

**Comment by rchipka** [comment]
@kadencethemes I'm using wordpress 5.0.3 with the built-in Gutenberg editor (not the plugin version).

I've added a workaround to my themes that fixes the issue, but I forgot to take a screenshot of the issue before-hand.

Here's the fix I'm using in case you're interested:

```js
wp.hooks.addFilter(
  'blocks.registerBlockType',
  'vbtk/blocks',
  function (settings, name) {
    if (!/^kadence\/(column|tab)$/.test(name)) {
      return settings;
    }

    // hide certain blocks from default block inserter

    if (!settings.supports) {
      settings.supports = {};
    }

    settings.supports.inserter = false;

    return settings;
  });
```

**Comment by kadencethemes** [comment]
yeah, it's not a big deal to add it just shouldn't matter because the parent is set, weird that I can't see it.

**Comment by kadencethemes** [comment]
This has been updated :)
