### ISSUE TITLE
Ask a favor

### ISSUE THREAD

**Issue by anwebdevelopers** [kadencethemes/kadence-blocks#2]
Hello! I am very impressed with your plugin! It is awesome!
I am a beginner WordPress developer. And I would like to learn how to create blocks for guttenberg, since it will soon be embedded in WordPress. Information on the Internet is not so much, especially such a level as your plugin and custom elements in it. And there is no information in Russian at all ... And I would like to ask you if you could give the uncompressed code of the file "blocks.build.js" as an example for studying. And I apologize if it is brazen. Contact email if needed anwebdev78@gmail.com

**Comment by kadencethemes** [comment]
Hey,
 So all of that un-minified JS is right in the src folder here: https://github.com/kadencethemes/kadence-blocks/tree/master/src

All those JS files including the ones in the inner folders are all combined together in the output. So you can view all the un-minified right there.

If you're getting into building blocks I suggest using this tool: https://github.com/ahmadawais/create-guten-block

That will really help you in getting started and understanding the src files and automate the compiling for you.

Let me know if that helps.

Ben

**Comment by anwebdevelopers** [comment]
Thanks a lot Ben! I hope that I will succeed)
