### ISSUE TITLE
Feature Request: 'Order' Setting for each column

### ISSUE THREAD

**Issue by bucketpress** [kadencethemes/kadence-blocks#21]
Will be very useful for users to be able to set the 'order' (text field) of each column for desktop and mobile. Since columns are rendered in flex and users are able to  change the layout for desktop, tablet and mobile, allowing users to set the order of the flex children (.wp-block-kadence-column) will be critical. 

Example use case - In a two or more column row layout:
An image is inserted on the last column. In mobile devices where the columns respond to become stacked one after another, the user wants to display this image on the top. With this set 'order' feature, the user can set order of this column to '-1' for mobile and make this possible.

**Comment by kadencethemes** [comment]
Currently, you can select to collapse from right to left or left to right. So your example is already possible. 

But having an override is a good idea. I'll put it on the feature request list.

**Comment by bucketpress** [comment]
Yes, having this individual column override will give users finer control, because the use is varied and in some cases it is not just a reverse order that users want - e.g. pushing a middle column (in a 3 column row) to the top (i.e. order: -1) when columns are stacked in mobile. Thanks!

**Comment by kadencethemes** [comment]
This has been added to the latest version.

Ben
