### ISSUE TITLE
Accordion suggestions, title font

### ISSUE THREAD

**Issue by toffebjorkskog** [kadencethemes/kadence-blocks#23]
I love the updates for 1.3.0
here are some suggestions to make it even better.

Accordion title:
- enable bold font
- enable uppercase

**Comment by kadencethemes** [comment]
Thanks for posting, if you choose a font family then based on the family you choose you can assign weights and styles that the font family supports. I'll look at adding a bold setting option that can show if no font family is selected.

I'll add a text transform setting.

Ben

**Comment by kadencethemes** [comment]
Both of these are now added.
