### ISSUE TITLE
Accordion suggestions, "remove this pane"

### ISSUE THREAD

**Issue by toffebjorkskog** [kadencethemes/kadence-blocks#24]
Right now you can add a new accordion pane via a button, but if you want to remove one you need to adjust the number of accordion panes in the right menu.

it would be good to be able to remove a pane via the cogwheel for that particular pane

**Comment by kadencethemes** [comment]
Thanks, I'll look into how this could work. Based on how things are written in Gutenberg the last accordion would be the only one that could be removed. Similar to how you can only add one at the end.

Ben

**Comment by kadencethemes** [comment]
You can now rearrange panes and remove the last one :)
