### ISSUE TITLE
Jumping when changing tabs

### ISSUE THREAD

**Issue by toffebjorkskog** [kadencethemes/kadence-blocks#27]
The client we are making a site for at the moment complained about that the browser scrolls to the top of the tab content when changing tabs.
According to the client they feel it is not necessary and a bit annoying.
Perhaps it could be a setting.

**Comment by kadencethemes** [comment]
Hey, this isn't something that the Kadence Blocks add. It likely means your running a script either from theme or plugin that is adding a scroll to anchor and is overriding the default behavior. 

See here: https://www.kadenceblocks.com/tabs-block/
