### ISSUE TITLE
What a amazing plugin! // Font Awesome future request :)

### ISSUE THREAD

**Issue by BeholdPL** [kadencethemes/kadence-blocks#28]
You read in my mind. This exacly I think about when I start using Guttenberg! This is one of the must-have right besides ACF.

I think it would be great to include Font Awesome. Then ... it will be total awesome :)

**Comment by kadencethemes** [comment]
Hey
 Thanks for posting!
 There are a lot of the font awesome icons included in our icon block, is there one, in particular, you are looking for?

Ben

**Comment by BeholdPL** [comment]
Hey :)

Probbably I missed any Font Awesome :D Sorry for confusion :)

I assume there is a possibility to create my own prebuild sections? Right now I'm startig working over my universal theme... with yours plugin it will be pleassure :)

**Comment by SJNBham** [comment]
It would be great to have the option to use Fontawesome Pro and choose which icons are loaded into the searchable catalog.
