### ISSUE TITLE
Create custom design library

### ISSUE THREAD

**Issue by BeholdPL** [kadencethemes/kadence-blocks#29]
Hi

I'm looking but I can't find in docs. Is there any way to create / include my own layouts, just like yours prebuilds layouts library? If not - is there any plans for that?

For example, I want design my own Hero image sections, code them and include as a part of theme for future design.

Thanks!

**Comment by kadencethemes** [comment]
Hey, you can currently do this through a filter, I'm considering adding an interface for this at some point. 

I outlined how to do it here, let me know if you have questions!
https://wordpress.org/support/topic/possible-to-edit-kadence-blocks-interface/#post-11146044

Ben
