### ISSUE TITLE
Container/Section Block

### ISSUE THREAD

**Issue by shazahm1** [kadencethemes/kadence-blocks#33]
Other block libraries such as [Ultimate Addons for Gutenberg](https://wordpress.org/plugins/ultimate-addons-for-gutenberg/) and [Stackable – Gutenberg Blocks](https://wordpress.org/plugins/stackable-ultimate-gutenberg-blocks/) have a container block. This would a a great addition to your library too.

I know you can add a Row Block set to a single column, but somehow the container blocks seem a little simpler to use when you do not need the row/columns feature set.

**Comment by shazahm1** [comment]
Scratch my reference to the Stackable Container block... only the  Ultimate Addons for Gutenberg Container block is what I'm looking for feature wise.

**Comment by kadencethemes** [comment]
Hey,
 Thanks for your suggestion. 

I won't be adding a container block separate from our row/layout block as that is exactly what our row layout block is for. Almost all the column controls are hidden if you select a single row layout so I don't agree that it's simpler to use and in fact, I think it's more confusing to have two blocks that do the same thing. 

With our Block Controls Manager, you will soon be able to turn off row controls so if you want to hide something to make the row/layout block even simpler you will be able to.

If there is something you are wanting to do that you can with Ultimate Addons for Gutenberg Container block let me know.

Ben

**Comment by lutrov** [comment]
To what extent are you working on offering the extent of blocks that Ultimate Addons for Gutenberg offers? Are the posts related blocks (including custom post type support) on the roadmap?

**Comment by kadencethemes** [comment]
Hey,
 We are working to add more blocks. The next release of the free plugin will have another one with efforts for a couple more in the coming weeks.

We have a really powerful Post grid/carousel block as part of our pro plugin. We plan to add custom post type support to it soon.
https://www.kadenceblocks.com/pro/

We also have a product carousel block in our pro plugin.

More post related blocks are in the works

Ben

**Comment by lutrov** [comment]
Hey Ben, your pro version is great value for money! I'd be interested in the post grid/carousel block, provided it had custom post type support. When is that likely to be the case?

**Comment by kadencethemes** [comment]
I should have that update out today or tomorrow at the latest :)

Ben

**Comment by lutrov** [comment]
Hey @kadencethemes, how's it going with the update?

**Comment by kadencethemes** [comment]
Hey, sorry I didn't post back here, I pushed out an update for pro with custom post type support the day after I posted here. It's part of pro.

Ben

**Comment by lutrov** [comment]
Thanks Ben. :-)
