### ISSUE TITLE
Margin/Padding Controls

### ISSUE THREAD

**Issue by shazahm1** [kadencethemes/kadence-blocks#36]
Margin and Padding control need added to the either the Icon block or the Adv Paragraph block (I know it already has before and after) or both. I'm trying to place an icon beside a heading.

Here's a screenshot and the fields I used as a [reusable block](https://www.pair.com/support/kb/gutenberg-editor-how-to-create-reusable-blocks/) exported as a JSON. This can be imported into WP on the Manage Reusable Block admin page so you can see.

![2019-03-14_11-31-13](https://user-images.githubusercontent.com/1185008/54370476-0eba6200-464e-11e9-9abd-aba37554a3df.png)

[styled-box-icon-heading-left.zip](https://github.com/kadencethemes/kadence-blocks/files/2967221/styled-box-icon-heading-left.zip)

**Comment by shazahm1** [comment]
I should not the screen shot show the two I methods I tried, the top is a 2-col row with the icon in the left and heading in the right. The bottom is a 1-col row with the icon floated left with a heading.

**Comment by kadencethemes** [comment]
Hey,
I will add margin controls in the next update. :)

Ben

**Comment by kadencethemes** [comment]
That update is out 👍

**Comment by shazahm1** [comment]
Thanks, I was able to use the margin on the Icon block media to get the desired layout.
