### ISSUE TITLE
Row Layout Block doesn't allow seperate setting for landscape and portrait

### ISSUE THREAD

**Issue by Freundschaft** [kadencethemes/kadence-blocks#38]
![image](https://user-images.githubusercontent.com/5065616/55364084-9540c180-54df-11e9-9d6b-957011d86f49.png)

row layout is great, but i can only setup a mobile layout for tablet and phone, without being able to specify if the target layout should be portrait or landscape.
as far as I see it it would be extremely helpful if I had five options there:

* desktop
* tablet portrait
* tablet landscape
* phone portrait
* phone landscape

**Comment by kadencethemes** [comment]
Hey,
 Thanks for your suggestions!
I'm not aware of any page builder doing that kind of a breakdown. One could make an argument that landscape phone is tablet portrait size, and landscape tablet is desktop size. Certainly very close in terms of pixels which is how media queries are currently set.

Can you give me some real-world examples of where you want to set the layout for "phone landscape" different from the tablet portrait?

Thanks!

**Comment by Freundschaft** [comment]
then there might be an issue with the selectors, since on landscape phone, I still get the phone table setting

https://www.fischer-smits.de/team/ on this site I have 

![image](https://user-images.githubusercontent.com/5065616/55425277-5d3e8a80-5582-11e9-91df-e1daac89401b.png)

**Comment by kadencethemes** [comment]
It just depends on what phone you are using. The pixels of phones are different.

The tablet size starts at 767px

I'm looking around at page builders to see if I can find any examples of others breaking down two media queries below 767px

**Comment by Freundschaft** [comment]
wouldnt it simply be possible to add a media query that checks for orientation: landscape or portrait?

**Comment by kadencethemes** [comment]
Kind of, But you still have to define sizes for which devices you are targeting. An IphoneX for example in landscape is wider than 767 so it would be using tablet sizes. 

Also, I've read that orientation is not fully supported. 

To get an idea of how complicated the media queries can get check out this page here: https://css-tricks.com/snippets/css/media-queries-for-standard-devices/

I can't find anything from elementor, brizy or beaver builder that does more then the then main sizes. 

Or course you can always use custom css and target something, it's just adding the extra controls which can be more overwelming then helpful. Espesially with device sizes being so different and phones creaping on tablet sizes.

**Comment by Freundschaft** [comment]
I see, in this case thanks for the trouble, I'll close this one then :)
