### ISSUE TITLE
Jarallax.js IE11 Issue

### ISSUE THREAD

**Issue by mojpe** [kadencethemes/kadence-blocks#39]
Hi just came across to a problem with kadence-blocks using jarallax.js in all other browsers work fine except in IE11 it is throwing and error "Object expected". I manage to overcome this problem setting the elementInViewport: null, in kt-init-parallax.js but is just temporary solution.
Is there any other way I can avoid this error?
Thank you in advance.

**Comment by kadencethemes** [comment]
Thanks for the bug report. I'll have this fixed with the next update!

Ben

**Comment by kadencethemes** [comment]
That update is live so I'm closing this.

Thanks again!
Ben
