### ISSUE TITLE
Icon List breaks when adding new lines

### ISSUE THREAD

**Issue by Jilson** [kadencethemes/kadence-blocks#40]
When hitting Enter/Return in the List Icon block, it breaks the preview and shows this error in the console: `TypeError: Cannot read property 'link' of undefined`

Version 1.5.2 - Twenty Nineteen - No other plugins activated.

**Comment by kadencethemes** [comment]
Thanks for posting, are you using the gutenberg plugin? Or wordpress 5.1.1?

Ben

**Comment by Jilson** [comment]
Wordpress 5.1.1. I see you updated this already and it no longer breaks when pressing return. Thank you for the quick fix.
