### ISSUE TITLE
Global max-width options for Row Layout width choices

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#41]
The Row Layout block comes with three width settings: Full width, Wide width, and Align center.

I'm currently coding CSS rules to control these widths on the front-end while a script transforms the front-end selectors to target the corresponding block in the Gutenberg editor.

Ideally I think these widths should be controllable by a setting in the admin dashboard.

This way Kadence Blocks can handle the way these changes are reflected in the editor and front-end.

This also (should) allow the row widths for the entire site to be updated in a single location.

If possible, it'd also be nice to control what each of the three width options should be for each of the available page/post/archive templates that have been registered on the site.

**Comment by kadencethemes** [comment]
Hey,
 So the Row Layout block does not come with these settings, that is part of Gutenberg and the row blocks just allows support for that. It's a really important distinction. These settings are not separate from Gutenberg, they are not Kadence Settings. And control over those widths was determined to be theme territory early on. In fact, themes can opt out of supporting those settings and then they simply will not show.

Overriding this creates a compatibility nightmare for me and would mean breaking from the standard way of doing things.

Perhaps there is space for an add-on that attempts to break the theme's control but I don't think if I developed that I would place it as part of the core Kadence Blocks settings. And for it to work right it would need to apply to all blocks that support wide and fullwidth.

Ben
