### ISSUE TITLE
Responsive text align settings on Column or Row Layout

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#43]
It'd be nice to be able to specify the text alignment at the Column or Row Layout level.

I've also run into situations where inner blocks are aligned left on desktop but should be centered on mobile.

There's no good way to do this currently within the editor.

**Comment by kadencethemes** [comment]
Thanks, I'll make sure this gets on my list.
Ben

**Comment by rchipka** [comment]
Thanks!

**Comment by kadencethemes** [comment]
This is out with version 1.5.4

Ben
