### ISSUE TITLE
Not proper html for div class

### ISSUE THREAD

**Issue by mlangone** [kadencethemes/kadence-blocks#44]
In the read more excerpt link the div class is missing an opening quote as seen here. Can this be fixed so that I can adjust the layout with CSS
<img width="432" alt="Screen Shot 2019-05-15 at 7 48 23 PM" src="https://user-images.githubusercontent.com/4027703/57823009-e7197000-774a-11e9-9432-2588afd3c563.png">

**Comment by kadencethemes** [comment]
Thanks for post, I just pushed out a fix. 

Ben
