### ISSUE TITLE
feature: Set default font in editor

### ISSUE THREAD

**Issue by bebjakub** [kadencethemes/kadence-blocks#45]
Hi, thanks a lot for this great plugin! :)
I have a feature idea. Is possible add to Font Family Options's modal field to choose default font in the editor? Maybe also with check opt "Load Google Font on Frontend".

Thanks

**Comment by kadencethemes** [comment]
Hey, on a per block basis you could choose a default, I'm working to get all the options available there. For example with the latest version you can choose a default font for the advanced heading block and choose the default for "load google font in frontend"
