### ISSUE TITLE
Advanced Button uses RichText but renders escaped HTML

### ISSUE THREAD

**Issue by vena** [kadencethemes/kadence-blocks#46]
The advanced button block uses a RichText component which allows things like newlines and bold text, but the rendered button escapes all of that.  Example:

![image](https://user-images.githubusercontent.com/867733/58284849-8d7ff980-7d79-11e9-9770-e1ada5e0adc2.png)

...renders as...

![image](https://user-images.githubusercontent.com/867733/58284877-9a9ce880-7d79-11e9-8c14-e78e56256b18.png)

**Comment by kadencethemes** [comment]
Thanks for posting about this, I am rewriting the button with some new features and some structure changes and will have this fixed with the next update.
