### ISSUE TITLE
Text Color settings on Row Layout

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#5]
Sometimes a Row Layout block can have a background or overlay whose color doesn't contrast well with the default body text color.

Row Layout blocks should have a "Text Color" setting that changes the default inherited text color for all child blocks.

**Comment by kadencethemes** [comment]
hmm thats interesting, I'll have to think through some options for that.

**Comment by rchipka** [comment]
@kadencethemes I'd think simply setting the CSS `color` property would be sufficient, as this will set a default that can be easily override on child blocks, for example a paragraph, by choosing a color setting on that specific block.

**Comment by rchipka** [comment]
This would use the built-in [ColorPicker](https://wordpress.org/gutenberg/handbook/designers-developers/developers/components/color-picker/) component, of course.

**Comment by rchipka** [comment]
Thank you!!
