### ISSUE TITLE
Color Pickers should respect `disableCustomColors` in block_editor_settings

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#51]
Looks like Kadence Blocks (or at least Row Layout) now has a color picker that supports a custom hex code or custom color section.

The built-in color picker will currently respect the theme's choice to disable custom color selection and enforce the selection of predefined colors.

Ideally the color customization options are hidden when this editor setting is active.

**Comment by rchipka** [comment]
See this page for more details:
https://developer.wordpress.org/block-editor/packages/packages-block-editor/#SETTINGS_DEFAULTS

**Comment by kadencethemes** [comment]
Thanks, Next version is going to have a setting inside Kadence Blocks controls to limit the custom color selection to specific user groups. Similar to how you can limit which fonts are available to choose from. That way you could set it up so wordpress admins could use custom colors it but you could turn it off for editors, etc. The goal is to add more control for freelancers. Thoughts on this?

**Comment by rchipka** [comment]
@kadencethemes I like that idea and actually have that specific need, but I think that it should respect the wordpress editor settings by default if possible.

Also, if it's not visibly supporting a developers gutenberg choices out of the box, any new Kadence Blocks user might be discouraged by the impression that the standard Gutenberg integration support is lacking.

**Comment by kadencethemes** [comment]
Just to follow up and close this, support for "disableCustomColors" this was added a while ago. 

Thanks!
