### ISSUE TITLE
Open tabs programatically

### ISSUE THREAD

**Issue by carcam** [kadencethemes/kadence-blocks#55]
I'm trying to switch tabs activation according to the anchor set in the url. For instance:

www.url.com/mypage#tab-2

will open tab-2 and so on. I have been looking but could not find an easy way to trigger the tab switch by javascript. Could you please provide a hint of what can I use for that?

Thank you!!

**Comment by kadencethemes** [comment]
Hey!
There is already a built-in function for this in the code.

https://www.kadenceblocks.com/tabs-block/#tab-tab2

Right-click on your tab and copy the link then use that.

Ben

**Comment by carcam** [comment]
Wow!! Easier than expected!! You are really awesome!! Thank you very much!!!

**Comment by kadencethemes** [comment]
You bet!
