### ISSUE TITLE
SVG icons broken in Twenty Nineteen frontend

### ISSUE THREAD

**Issue by pmmueller** [kadencethemes/kadence-blocks#56]
I have already reported this in support forum ([link](https://wordpress.org/support/topic/svg-icons-on-twenty-nineteen-broken/)), but here I can add a couple of screenshots to illustrate the problem. 

With Twenty Nineteen as active theme, in the block editor the icons are fine: 
![image](https://user-images.githubusercontent.com/1928205/62863477-2e42dd00-bd09-11e9-917a-cf29d6b7b412.png)

However, in the Twenty Nineteen frontend the icons do look weird:
![Bildschirmvideo aufnehmen 2019-08-12 um 14 05 36](https://user-images.githubusercontent.com/1928205/62863951-a65dd280-bd0a-11e9-877b-861ae97c7ac1.gif)

If I disable `fill: currentColor`in the Devtool, the icons look okay, but adding the rule `svg { fill: none; }` to Customizer > CSS does not work. It seems to fix icons like phone and envelope, but unfortunately other icons like e.g. a double arrow `»` disappear entirely.

**Comment by kadencethemes** [comment]
Thanks for all the images and information!

Here is a fix:

```
svg[fill="none"] {
    fill: none;
}
svg[fill="currentColor"] {
    fill: currentColor;
}
```

I'm trying to decide if this is really something I should have to add to the plugin. Can't see why the creators of Twenty nineteen would add this.

**Comment by pmmueller** [comment]
Thanx for the fix, and it works.
