### ISSUE TITLE
API, filter, or setting for Advanced Heading's "Font Family" choices

### ISSUE THREAD

**Issue by rchipka** [kadencethemes/kadence-blocks#6]
Ideally, a theme developer or site administrator could configure or limit the list of available font options as well as add new (non-google) font choices.

Additional "Font Family" options would be created by setting the option's label text as well as the actual CSS font-family name that should be used.

**Comment by kadencethemes** [comment]
I've been working to make the typography a more organized component and I'll make sure there is a filter put in for the options. With it, you could define your own array or push in some extras.

One thing to point out is that if you define your own custom fonts loading that font in the editor and the frontend would be up to you.

**Comment by kadencethemes** [comment]
Also should note that this filter would be a JS filter not something that could be done with PHP

**Comment by kadencethemes** [comment]
The filter has been added: https://github.com/kadencethemes/kadence-blocks/blob/master/src/typography-control.js#L222

**Comment by rchipka** [comment]
Thanks!
